---
apiVersion: v1
offerings:
  - name: terraform-ibm-resource-group
    kind: module
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: de458c9b-835d-4014-b11f-d61ea081e986
    examples:
      - name: new-resource-group
        mark_ready: true
      - name: existing-resource-group
        mark_ready: true
